{% set name = "boario" %}
{% set version = "0.5.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/boario-{{ version }}.tar.gz
  sha256: ea8500e921acf89b68e9d1e861399ff44e3e2d90fe17219967e91bdb17bf2d25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - coloredlogs >=15.0.1,<16.0.0
    - country_converter >=1.0.0,<2.0.0
    - dask-core >=2023
    - numpy <1.27
    - odfpy >=1.4.1,<2.0.0
    - pandas >=1.5
    - progressbar2 >=4.2.0,<5.0.0
    - pyarrow >=11
    - pymrio >=0.4
test:
  imports:
    - boario
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spjuhel/BoARIO
  summary: 'BoARIO : The Adaptative Regional Input Output model in python.'
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: 'BoARIO, is a python implementation project of the Adaptative Regional Input Output (ARIO) model'
  doc_url: https://spjuhel.github.io/BoARIO/boario-what-is.html
  dev_url: https://github.com/spjuhel/BoARIO


extra:
  recipe-maintainers:
    - spjuhel
