{% set python_min = "3.10" %}
{% set name = "boario" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/boario-{{ version }}.tar.gz
  sha256: 2058d96006eec4c376121e734dec93a01ad61a363a9fa414f9d8a34fd08ba60f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - coloredlogs >=15.0.1,<16.0.0
    - country_converter >=1.0.0,<2.0.0
    - dask-core >=2023
    - numpy <1.27
    - odfpy >=1.4.1,<2.0.0
    - pandas >=1.5
    - progressbar2 >=4.2.0,<5.0.0
    - pyarrow >=11
    - pymrio >=0.4
test:
  imports:
    - boario
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/spjuhel/BoARIO
  summary: 'BoARIO : The Adaptative Regional Input Output model in python.'
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: 'BoARIO, is a python implementation project of the Adaptative Regional Input Output (ARIO) model'
  doc_url: https://spjuhel.github.io/BoARIO/boario-what-is.html
  dev_url: https://github.com/spjuhel/BoARIO


extra:
  recipe-maintainers:
    - spjuhel
